spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.150.200:3306/zoj?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456